In [21]:
import numpy as np

In [12]:
file = open('ex1data1.txt', 'r')

In [13]:
lines = file.read().splitlines()

In [14]:
lines

['6.1101,17.592',
 '5.5277,9.1302',
 '8.5186,13.662',
 '7.0032,11.854',
 '5.8598,6.8233',
 '8.3829,11.886',
 '7.4764,4.3483',
 '8.5781,12',
 '6.4862,6.5987',
 '5.0546,3.8166',
 '5.7107,3.2522',
 '14.164,15.505',
 '5.734,3.1551',
 '8.4084,7.2258',
 '5.6407,0.71618',
 '5.3794,3.5129',
 '6.3654,5.3048',
 '5.1301,0.56077',
 '6.4296,3.6518',
 '7.0708,5.3893',
 '6.1891,3.1386',
 '20.27,21.767',
 '5.4901,4.263',
 '6.3261,5.1875',
 '5.5649,3.0825',
 '18.945,22.638',
 '12.828,13.501',
 '10.957,7.0467',
 '13.176,14.692',
 '22.203,24.147',
 '5.2524,-1.22',
 '6.5894,5.9966',
 '9.2482,12.134',
 '5.8918,1.8495',
 '8.2111,6.5426',
 '7.9334,4.5623',
 '8.0959,4.1164',
 '5.6063,3.3928',
 '12.836,10.117',
 '6.3534,5.4974',
 '5.4069,0.55657',
 '6.8825,3.9115',
 '11.708,5.3854',
 '5.7737,2.4406',
 '7.8247,6.7318',
 '7.0931,1.0463',
 '5.0702,5.1337',
 '5.8014,1.844',
 '11.7,8.0043',
 '5.5416,1.0179',
 '7.5402,6.7504',
 '5.3077,1.8396',
 '7.4239,4.2885',
 '7.6031,4.9981',
 '6.3328,1.4233',
 '6.3589,-1.4211',

In [19]:
arr = [float(l.split(',')) for l in lines]

TypeError: float() argument must be a string or a number, not 'list'

In [18]:
arr

[['6.1101', '17.592'],
 ['5.5277', '9.1302'],
 ['8.5186', '13.662'],
 ['7.0032', '11.854'],
 ['5.8598', '6.8233'],
 ['8.3829', '11.886'],
 ['7.4764', '4.3483'],
 ['8.5781', '12'],
 ['6.4862', '6.5987'],
 ['5.0546', '3.8166'],
 ['5.7107', '3.2522'],
 ['14.164', '15.505'],
 ['5.734', '3.1551'],
 ['8.4084', '7.2258'],
 ['5.6407', '0.71618'],
 ['5.3794', '3.5129'],
 ['6.3654', '5.3048'],
 ['5.1301', '0.56077'],
 ['6.4296', '3.6518'],
 ['7.0708', '5.3893'],
 ['6.1891', '3.1386'],
 ['20.27', '21.767'],
 ['5.4901', '4.263'],
 ['6.3261', '5.1875'],
 ['5.5649', '3.0825'],
 ['18.945', '22.638'],
 ['12.828', '13.501'],
 ['10.957', '7.0467'],
 ['13.176', '14.692'],
 ['22.203', '24.147'],
 ['5.2524', '-1.22'],
 ['6.5894', '5.9966'],
 ['9.2482', '12.134'],
 ['5.8918', '1.8495'],
 ['8.2111', '6.5426'],
 ['7.9334', '4.5623'],
 ['8.0959', '4.1164'],
 ['5.6063', '3.3928'],
 ['12.836', '10.117'],
 ['6.3534', '5.4974'],
 ['5.4069', '0.55657'],
 ['6.8825', '3.9115'],
 ['11.708', '5.3854'],
 ['5.7737', '2.4

In [22]:
a= [[2,3],[3,4]]

In [27]:
b = np.array(a, dtype = float)

In [28]:
b

array([[ 2.,  3.],
       [ 3.,  4.]])

In [29]:
b.shape

(2, 2)

In [30]:
c = np.array(arr, dtype = float)

In [31]:
c

array([[  6.1101 ,  17.592  ],
       [  5.5277 ,   9.1302 ],
       [  8.5186 ,  13.662  ],
       [  7.0032 ,  11.854  ],
       [  5.8598 ,   6.8233 ],
       [  8.3829 ,  11.886  ],
       [  7.4764 ,   4.3483 ],
       [  8.5781 ,  12.     ],
       [  6.4862 ,   6.5987 ],
       [  5.0546 ,   3.8166 ],
       [  5.7107 ,   3.2522 ],
       [ 14.164  ,  15.505  ],
       [  5.734  ,   3.1551 ],
       [  8.4084 ,   7.2258 ],
       [  5.6407 ,   0.71618],
       [  5.3794 ,   3.5129 ],
       [  6.3654 ,   5.3048 ],
       [  5.1301 ,   0.56077],
       [  6.4296 ,   3.6518 ],
       [  7.0708 ,   5.3893 ],
       [  6.1891 ,   3.1386 ],
       [ 20.27   ,  21.767  ],
       [  5.4901 ,   4.263  ],
       [  6.3261 ,   5.1875 ],
       [  5.5649 ,   3.0825 ],
       [ 18.945  ,  22.638  ],
       [ 12.828  ,  13.501  ],
       [ 10.957  ,   7.0467 ],
       [ 13.176  ,  14.692  ],
       [ 22.203  ,  24.147  ],
       [  5.2524 ,  -1.22   ],
       [  6.5894 ,   5.9966 ],
       [

In [32]:
c[:, 0]

array([  6.1101,   5.5277,   8.5186,   7.0032,   5.8598,   8.3829,
         7.4764,   8.5781,   6.4862,   5.0546,   5.7107,  14.164 ,
         5.734 ,   8.4084,   5.6407,   5.3794,   6.3654,   5.1301,
         6.4296,   7.0708,   6.1891,  20.27  ,   5.4901,   6.3261,
         5.5649,  18.945 ,  12.828 ,  10.957 ,  13.176 ,  22.203 ,
         5.2524,   6.5894,   9.2482,   5.8918,   8.2111,   7.9334,
         8.0959,   5.6063,  12.836 ,   6.3534,   5.4069,   6.8825,
        11.708 ,   5.7737,   7.8247,   7.0931,   5.0702,   5.8014,
        11.7   ,   5.5416,   7.5402,   5.3077,   7.4239,   7.6031,
         6.3328,   6.3589,   6.2742,   5.6397,   9.3102,   9.4536,
         8.8254,   5.1793,  21.279 ,  14.908 ,  18.959 ,   7.2182,
         8.2951,  10.236 ,   5.4994,  20.341 ,  10.136 ,   7.3345,
         6.0062,   7.2259,   5.0269,   6.5479,   7.5386,   5.0365,
        10.274 ,   5.1077,   5.7292,   5.1884,   6.3557,   9.7687,
         6.5159,   8.5172,   9.1802,   6.002 ,   5.5204,   5.0

In [35]:
data = np.loadtxt('ex1data1.txt', delimiter = ',')

In [36]:
X = data[:,0]
y = data[:,1]

In [38]:
m = len(y)
m

97

In [39]:
len(data)

97